@startmindmap

*[#DeepPink] Edge Computing

** Infrastructure
*** Management
****[#LightPink] Tools 
***** Remote access
****** DevicePlane
***** Identity 
****** Certificates
******* Hierarchy of identitites (IEEE 802.1AR Secure Device Identity)
****** Root of trust
****** Network address
****** Hardware UUID
****** User name / password
****** Mapping
***** Provisioning
****** Connect to existing devices
****** Laying infra on raw resources
****** Use gateways to establish connections
****** Zero touch
****** Hot swap
***** Software lifecycle management
****** Firmware
****** OS
***** Configuration
****** Network settings
****** Time
******* Sync
****** Configuration management
******* Templates
******** Asset Types
******* Rollbacks

*** Networking
**** Physical Networks
***** Field connectivity
***** Cloud side connectivity
**** Virtual Networks
***** Skupper
**** Quality of Service
**** Out of band
 

** Applications
*** Architecture
**** Service Mesh
**** Sequencing
**** Dependencies
**** Data flows (Application graph)
*** Lifecycle Management
**** Configuration
**** Deployment
***** Templating
***** Security
****** Device attestation
******* Multi-tenancy
****** Application attestation
****** State attestation
******* Location
******* Time
******* Health and resource monitoring
******** CPU
******** RAM
******** Environmental monitoring
********* Temperature
********* Moisture
********* Vibrations
********* Tampering
******** Storage
********* Flash health monitoring
********** Number of writes
******** Connectivity
********* Wireless
********* Wired
******** AI Accelerator
********* Number of cores
********* Types of silicon (model numbers)
******** I/O
********* USB controllers
********* Serial
********* GPIO (I2C / onboard)
********** On/off digital
********** Analog ports
********* PCIe / M2
********* MIPI CSI (cameras)
********* CANBUS (automotive)
********* MVB (rail) 

****** Ownership attestation


**** Monitoring
*** Build
**** Developer tools
***** Build System
****** Cross-compilation
****** Package Management
***** Sandbox
**** Pipelines
***** Upload to registry (CI/CD)
****** Marketplaces

**** Binary storage


** Data




** Management
***[#MediumSpringGreen] Edge Infrastructure Management
***[#LightGreen] Data Management
***[#Plum] Edge Applications
*** Provisioning and configuration


** Data
***[#Orange] Hardware
***[#Salmon] Virtualization
***[#Grey] Edge Sites
***[#DarkSeaGreen] Security
***[#LightPink] Tools

@endmindmap